package com.ludovic.vimont.randomcocktail.model

import com.squareup.moshi.JsonClass

@JsonClass(generateAdapter = true)
data class DrinksItem(
	val strDrinkFR: Any? = null,
	val strInstructionsDE: String? = null,
	val strDrinkZHHANS: Any? = null,
	val strDrinkZHHANT: Any? = null,
	val strIngredient10: String? = null,
	val strDrink: String? = null,
	val strIngredient12: String? = null,
	val strIngredient11: String? = null,
	val strIngredient14: String? = null,
	val strCategory: String? = null,
	val strAlcoholic: String? = null,
	val strIngredient13: String? = null,
	val strIngredient15: String? = null,
	val strCreativeCommonsConfirmed: String? = null,
	val strIBA: Any? = null,
	val strDrinkES: Any? = null,
	val strVideo: Any? = null,
	val strTags: Any? = null,
	val strInstructions: String? = null,
	val strIngredient1: String? = null,
	val strIngredient3: String? = null,
	val strIngredient2: String? = null,
	val strIngredient5: String? = null,
	val strIngredient4: String? = null,
	val strIngredient7: String? = null,
	val strIngredient6: String? = null,
	val strIngredient9: String? = null,
	val strInstructionsFR: Any? = null,
	val strIngredient8: String? = null,
	val idDrink: String? = null,
	val strInstructionsES: Any? = null,
	val strGlass: String? = null,
	val strDrinkDE: Any? = null,
	val strMeasure12: String? = null,
	val strMeasure13: String? = null,
	val strMeasure10: String? = null,
	val strMeasure11: String? = null,
	val dateModified: String? = null,
	val strDrinkAlternate: Any? = null,
	val strDrinkThumb: String? = null,
	val strInstructionsZHHANT: Any? = null,
	val strMeasure9: String? = null,
	val strMeasure7: String? = null,
	val strMeasure8: String? = null,
	val strMeasure5: String? = null,
	val strMeasure6: String? = null,
	val strMeasure3: String? = null,
	val strMeasure4: String? = null,
	val strMeasure1: String? = null,
	val strMeasure2: String? = null,
	val strInstructionsZHHANS: Any? = null,
	val strMeasure14: String? = null,
	val strMeasure15: String? = null
)